name: "Check Links in docs"
on:
  pull_request:
    types: [opened, synchronize]

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      actions: write
      pull-requests: write
      pages: read

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@8575951200e472d5f2d95c625da0c7bec8217c42 # v1.161.0
        with:
          ruby-version: '3.1.4'
          bundler-cache: true
          cache-version: 0

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.5.0
        with:
          args: --max-concurrency 30 --exclude-all-private --verbose --no-progress './**/*.md' './**/*.html'
          fail: false
          jobSummary: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with Jekyll to test
        run: bundle exec jekyll build --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production


#      - name: Create Issue From File
#        uses: peter-evans/create-issue-from-file@v4
#        with:
#          title: Link Checker Report
#          content-filepath: ./lychee/out.md
#          labels: |
#            report
#            automated issue
